server:
  port: 0
 # servlet:
 #   contextPath: /accounts
 # use-forward-headers: false


spring:
  profiles:
    active: test
  datasource:
    name: test
    url: jdbc:hsqldb:mem:test1://localhost/test1
    username:
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: none
      
security:
  oauth2:
    resource:
      filter-order: 3
      userInfoUri: http://localhost:5000/uaa/user
    client:
      client-id: LITSystem
      client-secret: LITSystem
 #     accessTokenUri: http://localhost:5000/uaa/user
 #     grant-type: client_credentials
 #     scope: system

---
  

   
spring:
  profiles: prod
 # data:
  #  rest:
   #   basePath: /v1
  datasource:
    url: jdbc:mysql://localhost:3306/LIT?characterEncoding=UTF-8
    username: root
    password: $LIT2016$
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
    show_sql: true
    hibernate:
      ddl-auto: update
      
security:
  oauth2:
    resource:
      filter-order: 3
      userInfoUri: http://localhost:8080/uaa/user #uaa-service/uaa/user
#    client:
#      clientId: LITSystem
#      clientSecret: LITSecret
#      accessTokenUri: http://localhost:8080/uaa/oauth/token
#      grant-type: client_credentials
#      scope: system
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka